version: "3.8"

services:
  db:
    image: postgres:16.3
    container_name: go-social-postgres-db
    environment:
      POSTGRES_DB: go-social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data:
