POST http://localhost:3000/v1/posts
Content-Type: "application/json"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb3BoZXJzb2NpYWwiLCJleHAiOjE3NDQ5MDkzNjAsImlhdCI6MTc0NDY1MDE2MCwiaXNzIjoiZ29waGVyc29jaWFsIiwibmJmIjoxNzQ0NjUwMTYwLCJzdWIiOjk2fQ.JkB2mfwUsP8jH0cE53e9ngNiCkKvQAAOknKsuXV6HrA

{
    "title": "Meu Post1",
    "content": "Conteúdo de teste",
    "tags": ["golang", "backend"]
}

###

GET http://localhost:3000/v1/posts/1



###
DELETE http://localhost:3000/v1/posts/1

###
PATCH http://localhost:3000/v1/posts/1
Content-Type: "application/json"

{
    "content": "Meu novo conteudo"

} 

# 
###



POST http://localhost:3000/v1/auth/user HTTP/1.1
Content-Type: "application/json"

{
  "email":"test@cadu112.com",
  "password":"12233",
  "username":"caduzinho122"
}



###
PUT  http://localhost:3000/v1/users/activate/a5bf3ff1-7b93-4889-8b52-81b8966240cb HTTP/1.1

###

POST http://localhost:3000/v1/auth/token HTTP/1.1
Content-Type: "application/json"

{
  "email":"test@cadu112.com",
  "password":"12233"
 
}
###
GET http://localhost:3000/v1/users/83
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb3BoZXJzb2NpYWwiLCJleHAiOjE3NDQ5MDg5NTEsImlhdCI6MTc0NDY0OTc1MSwiaXNzIjoiZ29waGVyc29jaWFsIiwibmJmIjoxNzQ0NjQ5NzUxLCJzdWIiOjk2fQ.EuqeAaJcNK_7jtGkFWTxgCoTkFWu4wybYqTRHxIVguI


###
PUT http://localhost:3000/v1/users/83/follow HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb3BoZXJzb2NpYWwiLCJleHAiOjE3NDQ5MDkzNjAsImlhdCI6MTc0NDY1MDE2MCwiaXNzIjoiZ29waGVyc29jaWFsIiwibmJmIjoxNzQ0NjUwMTYwLCJzdWIiOjk2fQ.JkB2mfwUsP8jH0cE53e9ngNiCkKvQAAOknKsuXV6HrA


{
  "user_id": 96
}
###
PUT http://localhost:3000/v1/users/2/unfollow HTTP/1.1
Content-Type: application/json

{
  "user_id": 1
}

###
GET http://localhost:3000/v1/users/feed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb3BoZXJzb2NpYWwiLCJleHAiOjE3NDQ5MDkzNjAsImlhdCI6MTc0NDY1MDE2MCwiaXNzIjoiZ29waGVyc29jaWFsIiwibmJmIjoxNzQ0NjUwMTYwLCJzdWIiOjk2fQ.JkB2mfwUsP8jH0cE53e9ngNiCkKvQAAOknKsuXV6HrA